#!/usr/bin/python3
"""Factorize as many numbers as possible
into a product of two smaller numbers.
"""
import sys

"""Open the file and read each line as an integer, sorting the numbers"""
with open(sys.argv[1], "r") as fp:
    lines = fp.readlines()
    numbers = [int(i) for i in lines]
    numbers.sort()

"""Iterate through each number and find its factorization"""
    for num in numbers:
        divisor = 2
        while divisor < num:
            if num % divisor == 0:
                factor = num // divisor
                print("{}={}*{}".format(num, factor, divisor))
                break
            else:
                divisor += 1

